# Fichier: mlflow/Dockerfile

# Partir de l'image officielle de MLflow
FROM ghcr.io/mlflow/mlflow:v2.9.2

# Installer le driver Python nécessaire pour se connecter à MySQL
# PyMySQL est un driver populaire et léger.
RUN pip install pymysql